apiVersion: batch/v1
kind: CronJob
metadata:
  name: collector-main
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: collector
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env: {{ toYaml .Values.env | nindent 16 }}
          restartPolicy: OnFailure
