FROM golang:1.24 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o setup setup.go

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/setup .
COPY --from=builder /app/database ./database
RUN chmod +x /app/setup
CMD ["./setup"]
