name: Dev Build and Test

on:
  push:
    branches:
      - dev

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up tag
      id: vars
      run: echo "tag=dev-$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push analyzer (dev)
      uses: docker/build-push-action@v5
      with:
        context: ./analyzer
        file: ./analyzer/Dockerfile
        push: true
        tags: docker.io/shin1031/phishing-analyzer:${{ steps.vars.outputs.tag }}
