name: Dev Build and Push to ECR

on:
  push:
    branches:
      - dev
    paths:
      - 'api-server/**'
      - 'analyzer/**'
      - 'collector/**'
      - '.github/workflows/**'

env:
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: 590183940165.dkr.ecr.ap-northeast-2.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up image tag
      id: vars
      run: echo "tag=dev-$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

    # 🧪 analyzer
    - name: Build and Push analyzer
      uses: docker/build-push-action@v5
      with:
        context: ./analyzer
        file: ./analyzer/Dockerfile
        push: true
        tags: |
          ${{ env.ECR_REGISTRY }}/phishing-analyze:${{ steps.vars.outputs.tag }}
          ${{ env.ECR_REGISTRY }}/phishing-analyze:latest

    # 🔐 api-server
    - name: Build and Push api-server
      uses: docker/build-push-action@v5
      with:
        context: ./api-server
        file: ./api-server/Dockerfile
        push: true
        tags: |
          ${{ env.ECR_REGISTRY }}/phishing-api-server:${{ steps.vars.outputs.tag }}
          ${{ env.ECR_REGISTRY }}/phishing-api-server:latest

    # 🕵️‍♂️ collector - main.go (CronJob)
    - name: Build and Push collector-main
      uses: docker/build-push-action@v5
      with:
        context: ./collector
        file: ./collector/Dockerfile
        push: true
        tags: |
          ${{ env.ECR_REGISTRY }}/phishing-collector-main:${{ steps.vars.outputs.tag }}
          ${{ env.ECR_REGISTRY }}/phishing-collector-main:latest

    # ⚙️ collector - setup.go (Job)
    - name: Build and Push collector-setup
      uses: docker/build-push-action@v5
      with:
        context: ./collector
        file: ./collector/Dockerfile.setup
        push: true
        tags: |
          ${{ env.ECR_REGISTRY }}/phishing-collector-setup:${{ steps.vars.outputs.tag }}
          ${{ env.ECR_REGISTRY }}/phishing-collector-setup:latest
